# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/adm_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdmWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 10, 181, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(280, 10, 141, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(530, 10, 141, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.persons_table = QtWidgets.QTableWidget(self.centralwidget)
        self.persons_table.setGeometry(QtCore.QRect(30, 50, 221, 501))
        self.persons_table.setShowGrid(True)
        self.persons_table.setObjectName("persons_table")
        self.persons_table.setColumnCount(2)
        self.persons_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.persons_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.persons_table.setHorizontalHeaderItem(1, item)
        self.persons_table.horizontalHeader().setVisible(False)
        self.persons_table.horizontalHeader().setStretchLastSection(True)
        self.persons_table.verticalHeader().setVisible(False)
        self.persons_table.verticalHeader().setStretchLastSection(False)
        self.btn_add_person = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_person.setGeometry(QtCore.QRect(220, 10, 31, 31))
        self.btn_add_person.setObjectName("btn_add_person")
        self.btn_add_build = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_build.setGeometry(QtCore.QRect(430, 10, 31, 31))
        self.btn_add_build.setObjectName("btn_add_build")
        self.buildings_table = QtWidgets.QTableWidget(self.centralwidget)
        self.buildings_table.setGeometry(QtCore.QRect(280, 50, 221, 501))
        self.buildings_table.setObjectName("buildings_table")
        self.buildings_table.setColumnCount(2)
        self.buildings_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.buildings_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.buildings_table.setHorizontalHeaderItem(1, item)
        self.buildings_table.horizontalHeader().setVisible(False)
        self.buildings_table.horizontalHeader().setStretchLastSection(True)
        self.buildings_table.verticalHeader().setVisible(False)
        self.keys_table = QtWidgets.QTableWidget(self.centralwidget)
        self.keys_table.setGeometry(QtCore.QRect(530, 50, 221, 501))
        self.keys_table.setObjectName("keys_table")
        self.keys_table.setColumnCount(2)
        self.keys_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.keys_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.keys_table.setHorizontalHeaderItem(1, item)
        self.keys_table.horizontalHeader().setVisible(False)
        self.keys_table.horizontalHeader().setStretchLastSection(True)
        self.keys_table.verticalHeader().setVisible(False)
        self.btn_del_build = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del_build.setGeometry(QtCore.QRect(470, 10, 31, 31))
        self.btn_del_build.setObjectName("btn_del_build")
        self.btn_add_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_key.setGeometry(QtCore.QRect(680, 10, 31, 31))
        self.btn_add_key.setObjectName("btn_add_key")
        self.btn_del_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del_key.setGeometry(QtCore.QRect(720, 10, 31, 31))
        self.btn_del_key.setObjectName("btn_del_key")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">ПОЛЬЗОВАТЕЛИ</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">ЗДАНИЯ</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">КЛЮЧИ</span></p></body></html>"))
        item = self.persons_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Person_name"))
        item = self.persons_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Person_ID"))
        self.btn_add_person.setText(_translate("MainWindow", "add_person"))
        self.btn_add_build.setText(_translate("MainWindow", "add_build"))
        item = self.buildings_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Building_Name"))
        item = self.buildings_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Building_ID"))
        item = self.keys_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Key_Name"))
        item = self.keys_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Key_ID"))
        self.btn_del_build.setText(_translate("MainWindow", "del_build"))
        self.btn_add_key.setText(_translate("MainWindow", "add_key"))
        self.btn_del_key.setText(_translate("MainWindow", "del_key"))
