# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/build_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Build_Create_Win(object):
    def setupUi(self, Build_Create_Win):
        Build_Create_Win.setObjectName("Build_Create_Win")
        Build_Create_Win.resize(400, 120)
        self.buttonBox = QtWidgets.QDialogButtonBox(Build_Create_Win)
        self.buttonBox.setGeometry(QtCore.QRect(240, 80, 151, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_4 = QtWidgets.QLabel(Build_Create_Win)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.build_name = QtWidgets.QLineEdit(Build_Create_Win)
        self.build_name.setGeometry(QtCore.QRect(10, 40, 381, 31))
        self.build_name.setObjectName("build_name")

        self.retranslateUi(Build_Create_Win)
        self.buttonBox.accepted.connect(Build_Create_Win.accept)  # type: ignore
        self.buttonBox.rejected.connect(Build_Create_Win.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Build_Create_Win)

    def retranslateUi(self, Build_Create_Win):
        _translate = QtCore.QCoreApplication.translate
        Build_Create_Win.setWindowTitle(_translate("Build_Create_Win", "Dialog"))
        self.label_4.setText(_translate("Build_Create_Win", "Название"))
