# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/key_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Key_Create_Win(object):
    def setupUi(self, Key_Create_Win):
        Key_Create_Win.setObjectName("Key_Create_Win")
        Key_Create_Win.resize(401, 263)
        self.buttonBox = QtWidgets.QDialogButtonBox(Key_Create_Win)
        self.buttonBox.setGeometry(QtCore.QRect(240, 220, 151, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_4 = QtWidgets.QLabel(Key_Create_Win)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Key_Create_Win)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.building_name = QtWidgets.QLineEdit(Key_Create_Win)
        self.building_name.setGeometry(QtCore.QRect(10, 40, 381, 31))
        self.building_name.setObjectName("building_name")
        self.key_name = QtWidgets.QLineEdit(Key_Create_Win)
        self.key_name.setGeometry(QtCore.QRect(10, 180, 381, 31))
        self.key_name.setObjectName("key_name")
        self.building_box = QtWidgets.QComboBox(Key_Create_Win)
        self.building_box.setGeometry(QtCore.QRect(10, 40, 381, 31))
        self.building_box.setObjectName("building_box")
        self.key_id = QtWidgets.QLineEdit(Key_Create_Win)
        self.key_id.setGeometry(QtCore.QRect(10, 110, 381, 31))
        self.key_id.setObjectName("key_id")
        self.label_7 = QtWidgets.QLabel(Key_Create_Win)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Key_Create_Win)
        self.buttonBox.accepted.connect(Key_Create_Win.accept)  # type: ignore
        self.buttonBox.rejected.connect(Key_Create_Win.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Key_Create_Win)

    def retranslateUi(self, Key_Create_Win):
        _translate = QtCore.QCoreApplication.translate
        Key_Create_Win.setWindowTitle(_translate("Key_Create_Win", "Dialog"))
        self.label_4.setText(_translate("Key_Create_Win", "ЗДАНИЕ"))
        self.label_6.setText(_translate("Key_Create_Win", "ИМЯ КЛЮЧА"))
        self.label_7.setText(_translate("Key_Create_Win", "ID"))
