# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 304)
        MainWindow.setStyleSheet("QDateTimeEdit{\n"
                                 "border-radius: 10px;\n"
                                 "border-style:inset;}\n"
                                 "\n"
                                 "QLineEdit{\n"
                                 "border-radius: 10px;\n"
                                 "border-style:inset;}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "color: #fff;\n"
                                 "text-shadow: -2px 2px #346392;\n"
                                 "background-color: rgb(162, 197, 225);\n"
                                 "background-image: linear-gradient(top, #6496c8, #346392);\n"
                                 "box-shadow: inset 0 0 0 1px #27496d;\n"
                                 "border: 2px;\n"
                                 "border-style: solid;\n"
                                 "border-color: rgb(255, 255, 255);\n"
                                 "border-radius: 15px; }\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    box-shadow: inset 0 0 0 1px #27496d,inset 0 5px 30px #193047;\n"
                                 "}\n"
                                 "\n"
                                 "QMainWindow{\n"
                                 "background: rgb(162, 197, 225)}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_adm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_adm.setGeometry(QtCore.QRect(10, 10, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_adm.setFont(font)
        self.btn_adm.setObjectName("btn_adm")
        self.btn_vahta = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vahta.setGeometry(QtCore.QRect(10, 80, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_vahta.setFont(font)
        self.btn_vahta.setObjectName("btn_vahta")
        self.btn_reports = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reports.setGeometry(QtCore.QRect(10, 150, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_reports.setFont(font)
        self.btn_reports.setObjectName("btn_reports")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(10, 220, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_adm.setText(_translate("MainWindow", "АДМИНИСТРИРОВАНИЕ"))
        self.btn_vahta.setText(_translate("MainWindow", "ВАХТА"))
        self.btn_reports.setText(_translate("MainWindow", "ОТЧЕТЫ"))
        self.btn_exit.setText(_translate("MainWindow", "ВЫХОД"))
