# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/report_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportWin(object):
    def setupUi(self, ReportWin):
        ReportWin.setObjectName("ReportWin")
        ReportWin.resize(814, 554)
        self.label_7 = QtWidgets.QLabel(ReportWin)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.key_id = QtWidgets.QLineEdit(ReportWin)
        self.key_id.setGeometry(QtCore.QRect(420, 110, 381, 31))
        self.key_id.setStyleSheet("QLineEdit{\n"
                                  "border-radius: 10px;\n"
                                  "border-style:inset;}")
        self.key_id.setObjectName("key_id")
        self.person_id = QtWidgets.QLineEdit(ReportWin)
        self.person_id.setGeometry(QtCore.QRect(10, 110, 381, 31))
        self.person_id.setStyleSheet("QLineEdit{\n"
                                     "border-radius: 10px;\n"
                                     "border-style:inset;}")
        self.person_id.setObjectName("person_id")
        self.label_8 = QtWidgets.QLabel(ReportWin)
        self.label_8.setGeometry(QtCore.QRect(420, 80, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(ReportWin)
        self.label_10.setGeometry(QtCore.QRect(420, 150, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(ReportWin)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_generate_a_report = QtWidgets.QPushButton(ReportWin)
        self.btn_generate_a_report.setGeometry(QtCore.QRect(10, 220, 791, 31))
        self.btn_generate_a_report.setStyleSheet("")
        self.btn_generate_a_report.setObjectName("btn_generate_a_report")
        self.person_name = QtWidgets.QLineEdit(ReportWin)
        self.person_name.setGeometry(QtCore.QRect(10, 180, 381, 31))
        self.person_name.setStyleSheet("QLineEdit{\n"
                                       "border-radius: 10px;\n"
                                       "border-style:inset;}")
        self.person_name.setObjectName("person_name")
        self.key_name = QtWidgets.QLineEdit(ReportWin)
        self.key_name.setGeometry(QtCore.QRect(420, 180, 381, 31))
        self.key_name.setStyleSheet("QLineEdit{\n"
                                    "border-radius: 10px;\n"
                                    "border-style:inset;}")
        self.key_name.setObjectName("key_name")
        self.history_table = QtWidgets.QTableWidget(ReportWin)
        self.history_table.setEnabled(True)
        self.history_table.setGeometry(QtCore.QRect(10, 260, 791, 281))
        self.history_table.setObjectName("history_table")
        self.history_table.setColumnCount(5)
        self.history_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.history_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(4, item)
        self.history_table.horizontalHeader().setStretchLastSection(True)
        self.label_9 = QtWidgets.QLabel(ReportWin)
        self.label_9.setGeometry(QtCore.QRect(420, 10, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(ReportWin)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.date_from = QtWidgets.QDateTimeEdit(ReportWin)
        self.date_from.setGeometry(QtCore.QRect(10, 40, 381, 31))
        self.date_from.setStyleSheet("QDateTimeEdit{\n"
                                     "border-radius: 10px;\n"
                                     "border-style:inset;}")
        self.date_from.setWrapping(False)
        self.date_from.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.date_from.setCalendarPopup(True)
        self.date_from.setObjectName("date_from")
        self.date_to = QtWidgets.QDateTimeEdit(ReportWin)
        self.date_to.setGeometry(QtCore.QRect(420, 40, 381, 31))
        self.date_to.setStyleSheet("QDateTimeEdit{\n"
                                   "border-radius: 10px;\n"
                                   "border-style:inset;}")
        self.date_to.setCalendarPopup(True)
        self.date_to.setObjectName("date_to")

        self.retranslateUi(ReportWin)
        QtCore.QMetaObject.connectSlotsByName(ReportWin)

    def retranslateUi(self, ReportWin):
        _translate = QtCore.QCoreApplication.translate
        ReportWin.setWindowTitle(_translate("ReportWin", "Form"))
        self.label_7.setText(_translate("ReportWin", "PERSON ID"))
        self.label_8.setText(_translate("ReportWin", "KEY ID"))
        self.label_10.setText(_translate("ReportWin", "ИМЯ КЛЮЧА"))
        self.label_4.setText(_translate("ReportWin", "ИМЯ ПОЛЬЗОВАТЕЛЯ"))
        self.btn_generate_a_report.setText(_translate("ReportWin", "СФОРМИРОВАТЬ ОТЧЕТ"))
        item = self.history_table.horizontalHeaderItem(0)
        item.setText(_translate("ReportWin", "Date"))
        item = self.history_table.horizontalHeaderItem(1)
        item.setText(_translate("ReportWin", "ThisReturn"))
        item = self.history_table.horizontalHeaderItem(2)
        item.setText(_translate("ReportWin", "Key"))
        item = self.history_table.horizontalHeaderItem(3)
        item.setText(_translate("ReportWin", "Person"))
        item = self.history_table.horizontalHeaderItem(4)
        item.setText(_translate("ReportWin", "Comment"))
        self.label_9.setText(_translate("ReportWin", "TO"))
        self.label_11.setText(_translate("ReportWin", "FROM"))
