# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/vahta_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VahtaWindow(object):
    def setupUi(self, VahtaWindow):
        VahtaWindow.setObjectName("VahtaWindow")
        VahtaWindow.resize(313, 317)
        self.centralwidget = QtWidgets.QWidget(VahtaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_give_the_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_give_the_key.setGeometry(QtCore.QRect(10, 10, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_give_the_key.setFont(font)
        self.btn_give_the_key.setObjectName("btn_give_the_key")
        self.btn_return_the_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_return_the_key.setGeometry(QtCore.QRect(10, 80, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_return_the_key.setFont(font)
        self.btn_return_the_key.setObjectName("btn_return_the_key")
        self.btn_key_report = QtWidgets.QPushButton(self.centralwidget)
        self.btn_key_report.setGeometry(QtCore.QRect(10, 150, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_key_report.setFont(font)
        self.btn_key_report.setObjectName("btn_key_report")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(10, 220, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        VahtaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VahtaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 21))
        self.menubar.setObjectName("menubar")
        VahtaWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VahtaWindow)
        self.statusbar.setObjectName("statusbar")
        VahtaWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VahtaWindow)
        QtCore.QMetaObject.connectSlotsByName(VahtaWindow)

    def retranslateUi(self, VahtaWindow):
        _translate = QtCore.QCoreApplication.translate
        VahtaWindow.setWindowTitle(_translate("VahtaWindow", "MainWindow"))
        self.btn_give_the_key.setText(_translate("VahtaWindow", "ВЫДАТЬ КЛЮЧ"))
        self.btn_return_the_key.setText(_translate("VahtaWindow", "ПРИНЯТЬ КЛЮЧ"))
        self.btn_key_report.setText(_translate("VahtaWindow", "ДАННЫЕ О КЛЮЧЕ"))
        self.btn_exit.setText(_translate("VahtaWindow", "ВЫХОД"))
